language: java
jdk:
- oraclejdk8
sudo: true
install: "./server -a"
script: "./server -k"
deploy:
  provider: releases
  api_key:
    secure: I6bskqzPyrpVt8PUzcXj3h7jiXb3Y0iRyDhsaKt5RkNK8aEKgPSM+RgtRCZIfbv9+J8IZCMJ3gFS8ght556DnDHWos90LfuNfTx6K2Fpi4eee42AjfSL/tkEayiJh+3INBOv2bS0F2X6hrfGIs3AeW2d4dbn5I2i8EK0cZKILw+uw7QXsbtUN5K/pyRaPTXtD8uy9VVa0ftwRJhzfSjjkW9lNKSpyACy4JEIvuCvvZ0kCb+/YwRyWpOgTcVF47Wzbogb2jayAoewg91O9uq6VLgtaOhbjKvS/XLWfVmSgbQkZJdbWNI/sMdTBDjCCv7CBr3PQRO8rOpIH3W/Moh84c4qPscNQg/yCFAzCz1bzboqnqqO6pc4Y65wEse2xv8jqjX10ucTkjZ8y3P+kbOgYwkTvBjR8I2lKoC4ClGDjOQ0nRZ5vRG+uq5RIkl/YFDrmXrrqwRZi5uX3ZvcU+uFyqmc7+tGCY6MFKNnJoQZHahXGcz0PmtpzuXthY87Clf6z/EHuN3Ug7jOGcZNH/6eVbXmoOKJuJD2h0zOoW0sVVLDCf+erM6oJypsO4P8yqnKF0xUE1OEuXdNH40hK0XCQLmtgVCZ1ZoWI6Gq7aMJ2vs1eBzaVJDuA8ptjhZpIj9IEQldf1n4tEo+JTlrv/1NOFyNLuPl3E3O8o2O5VxAtcQ=
  file:
    - releng/com.aiziyuer.sprite/target/products/SpriteApp-win32.win32.x86.zip
   - releng/com.aiziyuer.sprite/target/products/SpriteApp-win32.win32.x86_64.zip
   - releng/com.aiziyuer.sprite/target/products/SpriteApp-linux.gtk.x86_64.zip
   - releng/com.aiziyuer.sprite/target/products/SpriteApp-macosx.cocoa.x86_64.zip
  on:
    repo: aiziyuer/SpriteApp
